spring:
  mvc:
    async:
      request-timeout: 30000

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5444/keycloak
    username: keycloak
    password: keycloak
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 6868


keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8090}
  realm: ${KEYCLOAK_REALM:SplitWalletRealm}
  resource: ${KEYCLOAK_CLIENT:SplitWalletClient}
  public-client: false
  bearer-only: false
  principal-attribute: preferred_username
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:wbx7FFl3Gz9iWRXgmLZqmoczuuujJAjU}

keycloak-admin:
  realm: ${keycloak.realm}
  client-id: ${keycloak.resource}
  url: ${keycloak.auth-server-url}
  secret: ${keycloak.credentials.secret}
