server:
  port: 6868
spring:
  application:
    name: SplitWalletServer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5431/postgres
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
jwt_secret : PukSrenc